# Basic Python

## 1. Split this string

In [1]:
s = "Hi there Sam!"

In [2]:
x=s.split()
print(x)

['Hi', 'there', 'Sam!']


*`italicized text`*## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [3]:
planet = "Earth"
diameter = 12742

In [7]:
print("The diameter of {name} is {dist} kilometers.".format(name = "Earth", dist = 12742))

The diameter of Earth is 12742 kilometers.


## 3. In this nest dictionary grab the word "hello"

In [18]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [19]:
d['k1'][3]['tricky'][3]['target'][3]

'hello'

# Numpy

In [5]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [15]:
arr1=np.zeros(10)
print("An array of 10 zeros:")
print(arr1)


An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [16]:
arr2=np.ones(10)*5
print("An array of 10 fives:")
print(arr2)

An array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 5. Create an array of all the even integers from 20 to 35

In [6]:
arr=np.arange(20,35,2)
print(arr)

[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [9]:
np.arange(0,9).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 7. Concatinate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [22]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
con = np.concatenate((a, b))
print(con)

[1 2 3 4 5 6]


# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [23]:
import pandas as pd


In [24]:
data = [['a', 97], ['b', 98], ['c', 99]]
df = pd.DataFrame(data, columns=['Letter', 'ASCII'])
df

Letter  ASCII
0      a     97
1      b     98
2      c     99

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [31]:
import datetime
date1 = date(2023, 1, 1)
date2 = date(2023, 2, 10)
K = (date2-date1).days + 1
res = [date1 + datetime.timedelta(days=idx) for idx in range(K)]
print(str(res))

[datetime.date(2023, 1, 1), datetime.date(2023, 1, 2), datetime.date(2023, 1, 3), datetime.date(2023, 1, 4), datetime.date(2023, 1, 5), datetime.date(2023, 1, 6), datetime.date(2023, 1, 7), datetime.date(2023, 1, 8), datetime.date(2023, 1, 9), datetime.date(2023, 1, 10), datetime.date(2023, 1, 11), datetime.date(2023, 1, 12), datetime.date(2023, 1, 13), datetime.date(2023, 1, 14), datetime.date(2023, 1, 15), datetime.date(2023, 1, 16), datetime.date(2023, 1, 17), datetime.date(2023, 1, 18), datetime.date(2023, 1, 19), datetime.date(2023, 1, 20), datetime.date(2023, 1, 21), datetime.date(2023, 1, 22), datetime.date(2023, 1, 23), datetime.date(2023, 1, 24), datetime.date(2023, 1, 25), datetime.date(2023, 1, 26), datetime.date(2023, 1, 27), datetime.date(2023, 1, 28), datetime.date(2023, 1, 29), datetime.date(2023, 1, 30), datetime.date(2023, 1, 31), datetime.date(2023, 2, 1), datetime.date(2023, 2, 2), datetime.date(2023, 2, 3), datetime.date(2023, 2, 4), datetime.date(2023, 2, 5), datet

In [39]:
from datetime import date, timedelta
d = timedelta(days=1)
start_date = date(2023,1,1)
end_date = date(2023,2,11)
for i in range((end_date - start_date).days):
    print(start_date + i*d)

2023-01-01
2023-01-02
2023-01-03
2023-01-04
2023-01-05
2023-01-06
2023-01-07
2023-01-08
2023-01-09
2023-01-10
2023-01-11
2023-01-12
2023-01-13
2023-01-14
2023-01-15
2023-01-16
2023-01-17
2023-01-18
2023-01-19
2023-01-20
2023-01-21
2023-01-22
2023-01-23
2023-01-24
2023-01-25
2023-01-26
2023-01-27
2023-01-28
2023-01-29
2023-01-30
2023-01-31
2023-02-01
2023-02-02
2023-02-03
2023-02-04
2023-02-05
2023-02-06
2023-02-07
2023-02-08
2023-02-09
2023-02-10


## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [11]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [21]:
import pandas as pd  
df = pd.DataFrame(lists, columns =['S.No.', 'Name' , 'Count'])
print(df)

   S.No. Name  Count
0      1  aaa     22
1      2  bbb     25
2      3  ccc     24
